#!/usr/bin/env python3

import os
import sys

def whereis(filename):
    for path in os.environ["PATH"].split(os.pathsep):
        fullpath = os.path.join(path, filename)
        if os.path.exists(fullpath):
            return fullpath
    return None

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: whereis <filename>")
        sys.exit(1)
    filename = sys.argv[1]
    fullpath = whereis(filename)
    if fullpath is not None:
        print(fullpath)
    else:
        print("File not found.")
        sys.exit(1)
